language: ruby

sudo: false

matrix:
  include:
    - os: linux
      sudo: 9000
    - os: osx
      osx_image: xcode7.1

before_install:
  - gem install bundler
before_script:
  - bundle install
  - git clone https://github.com/mruby/mruby
script: "bundle exec rake test"
